### ISSUE TITLE
Shuttle module | Register Shuttle

### ISSUE THREAD

**Issue by kkmuthuselvam-kumaravel** [fssa-batch3/sec_a_muthuselvam.kumaravel__corejava_project_2#10]
# Create Shuttle Process

### User Story

As a admin, I want to be able to create new shuttle for the company. If the  shuttle id already exists for company, the system should display an error message indicating that the shuttle id already exists.

### Task

- [x] Implement Data Access Object (DAO) Layer.
- [x] Implement Service Layer.
- [x]  Create JUnit Test Cases.
- [x] Ensure that the tests cases are passing.
- [ ]  Write clear and concise comments in the code to explain complex logic.

### DAO:

-  createShuttle()

### Service:

-  registerShuttle()

### Junit Test:
-  testShuttleRegisterSuccess()
-  testNullInput()

### Estimation:
- 4hrs
